Create uthara.md
Leapcode-Open/landingpage pull request #375
Opened 2020-10-18 14:26 UTC by c4c0dee

2020-10-18 19:02 UTC, stanly-johnson requested changes
Please add `bio` field

2020-10-19 06:46 UTC, c4c0dee commented
updated bio

2020-10-19 06:47 UTC, c4c0de approved these changes

2020-10-19 17:27 UTC, stanly-johnson approved these changes

2020-10-19 17:27 UTC, merged